sudo: required
dist: trusty
language: generic

env:
  # This will check any ROS distro supported on this OS
  # checking devel and install separately so that they don't influence each other (dependencies, path, env, etc.)
  - CI_ROS_DISTRO=indigo ROS_FLOW=devel
  - CI_ROS_DISTRO=indigo ROS_FLOW=install
  - CI_ROS_DISTRO=jade ROS_FLOW=devel
  - CI_ROS_DISTRO=jade ROS_FLOW=install

install:
# Add ROS repositories
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
# Install and initialize rosdep
  - sudo apt-get install python-rosdep -y
  - sudo `which rosdep` init
  - rosdep update
# Use rosdep to install pyros-setup's dependencies
  - rosdep install --default-yes --from-paths ./ --rosdistro $CI_ROS_DISTRO

script:
  # full ROS setup, build and test
  # rospack find is TMP. debugging travis env here...
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash && rospack profile && rospack find catkin_pip
  - cat /opt/ros/$CI_ROS_DISTRO/share/catkin_pip/package.xml
  - mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=./install
  - if [ "$ROS_FLOW" == "devel" ]; then (make -j1 && source devel/setup.bash && make -j1 tests && make -j1 run_tests && catkin_test_results .); fi
  - if [ "$ROS_FLOW" == "install" ]; then (make -j1 install && source install/setup.bash && py.test --pyargs pyzmp); fi

notifications:
  email: false
